"""empty message

Revision ID: f0abc4e5ff60
Revises: f816096b50d8
Create Date: 2020-12-04 20:18:35.745090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0abc4e5ff60'
down_revision = 'f816096b50d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('booked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('services_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person'], ['user.id'], ),
    sa.ForeignKeyConstraint(['services_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booked_timestamp'), 'booked', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booked_timestamp'), table_name='booked')
    op.drop_table('booked')
    op.drop_table('services')
    # ### end Alembic commands ###
